[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.15"

[features]
resolution = true
skip-lint = false

# Anchor.toml
[programs.devnet]
credit_score_oracle = "49WpJBeDzwbeR1ApMcWkb2A9agTWQMuwVKvc9vnFqJBx"
lending_pool = "CHh7a34pf33QKEZN1enFS6f2gcXGEU8Nrzo8htfs47gr"
agent_permissions = "6cKABjL45MFFJPAZ9EbJJjNxbNRJpGUVhbJLFHako39R"


[programs.localnet]
credit_score_oracle = "49WpJBeDzwbeR1ApMcWkb2A9agTWQMuwVKvc9vnFqJBx"
lending_pool = "CHh7a34pf33QKEZN1enFS6f2gcXGEU8Nrzo8htfs47gr"
agent_permissions = "6cKABjL45MFFJPAZ9EbJJjNxbNRJpGUVhbJLFHako39R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run vitest run --globals tests/integration/01_golden_path.ts tests/integration/02_default_path.ts tests/integration/03_to_08_scenarios.ts tests/security/attack_vectors.ts tests/security/escrow_unauthorized.ts"
