/**
 * @module WalletService
 * @description Core WDK wallet operations for CredAgent agents on Solana.
 *
 * SECURITY INVARIANTS (verified by tests + audit checklist):
 * ──────────────────────────────────────────────────────────
 * S1. Seed phrases generated by WDK CSPRNG, stored in #seeds (private field), NEVER logged.
 * S2. Private keys accessed ONLY inside WDK sign internals — never returned, never stored.
 * S3. Every public method validates ALL inputs BEFORE any WDK / RPC call.
 * S4. Transfer amounts validated: > 0, <= MAX_TRANSFER, finite, integer-safe.
 * S5. Addresses validated as base58 Solana pubkeys (32-44 chars, no ambiguous chars).
 * S6. Agent IDs validated: 1-64 chars, no path traversal chars.
 * S7. Every operation logged to AuditLog (sans secrets) with timing.
 * S8. Rate limiting: configurable max ops/hour per agent.
 * S9. No floating point used for financial calculations — BigInt only.
 */

import WDK from '@tetherto/wdk';
import WalletManagerSolana from '@tetherto/wdk-wallet-solana';
import { validate } from './validation.js';
import { AuditLog } from './auditLog.js';
import { generate24WordSeedPhrase } from './seedPhrase.js';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import 'dotenv/config';

// ═══════════════════════════════════════════
// Constants
// ═══════════════════════════════════════════
const DEFAULT_RPC = 'https://api.devnet.solana.com';
const DEFAULT_WS  = 'wss://api.devnet.solana.com/';
const DEFAULT_MAX_FEE = 10_000_000; // 0.01 SOL in lamports
const MAX_SOL_TRANSFER = 100_000_000_000n;   // 100 SOL safety cap
const MAX_SPL_TRANSFER  = 1_000_000_000_000n; // 1M tokens (6 dec) safety cap
const DEFAULT_RATE_LIMIT = 200; // max ops/hour per agent

/**
 * Core WDK wallet service for CredAgent.
 * Manages agent wallets, SPL token operations, and signing.
 */
export class WalletService {
  /** @type {Map<string, AgentRecord>} */
  #agents = new Map();

  /** @type {Map<string, string>} SECURITY: private field — inaccessible externally */
  #seeds = new Map();

  /** @type {Map<string, number[]>} rate limit: agentId → timestamps */
  #rateBuckets = new Map();

  #audit;
  #config;
  #walletStorePath;

  /**
   * @param {object} config
   * @param {string} [config.rpcUrl]
   * @param {string} [config.wsUrl]
   * @param {number} [config.transferMaxFee] lamports
   * @param {number} [config.rateLimitPerHour]
   */
  constructor(config = {}) {
    this.#config = Object.freeze({
      rpcUrl:           config.rpcUrl           || process.env.WDK_SOLANA_RPC_URL || DEFAULT_RPC,
      wsUrl:            config.wsUrl            || process.env.SOLANA_WS_URL       || DEFAULT_WS,
      transferMaxFee:   Number(config.transferMaxFee || process.env.WDK_TRANSFER_MAX_FEE || DEFAULT_MAX_FEE),
      rateLimitPerHour: config.rateLimitPerHour || DEFAULT_RATE_LIMIT,
      stateDir:         config.stateDir         || path.resolve(process.cwd(), '.mcp-state'),
      walletStateEncryptionKey:
        config.walletStateEncryptionKey
          || process.env.WALLET_STATE_ENCRYPTION_KEY
          || (process.env.NODE_ENV === 'test' ? 'test-only-wallet-state-key' : ''),
    });
    this.#audit = new AuditLog();
    this.#walletStorePath = path.join(this.#config.stateDir, 'wallets.json');
  }

  // ═══════════════════════════════════════
  // T1B.1 — Wallet Creation
  // ═══════════════════════════════════════

  /**
   * Create a new self-custodial Solana wallet for an agent.
   *
   * SECURITY:
   * - 24-word BIP-39 seed generated by WDK CSPRNG
   * - Seed stored in #seeds private field (JS private class field)
   * - Only the Solana public address is returned — NEVER the seed
   *
   * @param {string} agentId unique identifier (1-64 chars, no special chars)
   * @returns {Promise<{agentId: string, address: string, chain: string}>}
   */
  async createAgentWallet(agentId) {
    validate.agentId(agentId);

    if (this.#agents.has(agentId)) {
      throw new Error(`WALLET_EXISTS: Agent "${agentId}" already has a wallet`);
    }

    const t0 = performance.now();

    // AUDIT[S1]: WDK generates 24-word cryptographically secure seed
    const seed = generate24WordSeedPhrase();

    // AUDIT[S1]: Seed stored in private field — inaccessible outside this class
    this.#seeds.set(agentId, seed);

    const record = await this.#instantiateWalletRecord(agentId, seed, Date.now());

    this.#agents.set(agentId, record);

    await this.#persistWallets();

    this.#audit.log('createWallet', agentId, { chain: 'solana' }, record.address, performance.now() - t0);

    // AUDIT[S2]: Return address only — seed and keys never exposed
    return { agentId, address: record.address, chain: 'solana' };
  }

  // ═══════════════════════════════════════
  // T1B.1 — Balance Queries
  // ═══════════════════════════════════════

  /**
   * Get native SOL balance in lamports.
   * @param {string} agentId
   * @returns {Promise<{token: string, lamports: string, sol: string}>}
   */
  async getSolBalance(agentId) {
    validate.agentId(agentId);
    const agent = this.#requireAgent(agentId);
    const t0 = performance.now();

    const balance = await agent.account.getBalance();

    const result = {
      token: 'SOL',
      lamports: String(balance),
      sol: (Number(balance) / 1e9).toFixed(9),
    };

    this.#audit.log('getSolBalance', agentId, {}, result.lamports, performance.now() - t0);
    return result;
  }

  /**
   * Get SPL token balance for a specific mint.
   * @param {string} agentId
   * @param {string} tokenMint base58 SPL token mint address
   * @returns {Promise<{token: string, rawBalance: string}>}
   */
  async getTokenBalance(agentId, tokenMint) {
    validate.agentId(agentId);
    validate.solanaAddress(tokenMint);
    const agent = this.#requireAgent(agentId);
    const t0 = performance.now();

    const balance = await agent.account.getTokenBalance(tokenMint);

    const result = {
      token: tokenMint,
      rawBalance: String(balance),
    };

    this.#audit.log('getTokenBalance', agentId, { mint: tokenMint.slice(0, 8) + '...' }, result.rawBalance, performance.now() - t0);
    return result;
  }

  /**
   * Get native SOL balance for any external address via raw RPC.
   * Read-only helper for collection/preflight logic.
   *
   * @param {string} address
   * @returns {Promise<{token: string, lamports: string, sol: string, owner: string}>}
   */
  async getExternalSolBalance(address) {
    validate.solanaAddress(address);
    const t0 = performance.now();

    const resp = await this.#rpc('getBalance', [address, { commitment: 'confirmed' }]);
    const lamports = String(resp?.value ?? 0);
    const result = {
      token: 'SOL',
      owner: address,
      lamports,
      sol: (Number(lamports) / 1e9).toFixed(9),
    };

    this.#audit.log('getExternalSolBalance', 'external', {
      owner: address.slice(0, 8) + '...',
    }, result.lamports, performance.now() - t0);
    return result;
  }

  /**
   * Inspect an external owner's SPL token position, including delegation.
   * Read-only helper for installment preflight checks.
   *
   * @param {string} ownerAddress
   * @param {string} tokenMint
   * @param {string} [delegateTo]
   * @returns {Promise<{token: string, owner: string, rawBalance: string, delegatedAmount: string, delegate: string|null, delegationSatisfied: boolean|null}>}
   */
  async getExternalTokenPosition(ownerAddress, tokenMint, delegateTo = undefined) {
    validate.solanaAddress(ownerAddress);
    validate.solanaAddress(tokenMint);
    if (delegateTo !== undefined) validate.solanaAddress(delegateTo);
    const t0 = performance.now();

    const resp = await this.#rpc('getTokenAccountsByOwner', [
      ownerAddress,
      { mint: tokenMint },
      { encoding: 'jsonParsed', commitment: 'confirmed' },
    ]);

    const accounts = resp?.value || [];
    let rawBalance = 0n;
    let delegatedAmount = 0n;
    let delegate = null;

    for (const item of accounts) {
      const info = item?.account?.data?.parsed?.info;
      if (!info?.tokenAmount?.amount) continue;
      rawBalance += BigInt(info.tokenAmount.amount);

      if (info.delegate && info.delegatedAmount?.amount) {
        const currentDelegated = BigInt(info.delegatedAmount.amount);
        if (currentDelegated > delegatedAmount) {
          delegatedAmount = currentDelegated;
          delegate = info.delegate;
        }
      }
    }

    const result = {
      token: tokenMint,
      owner: ownerAddress,
      rawBalance: String(rawBalance),
      delegatedAmount: String(delegatedAmount),
      delegate,
      delegationSatisfied: delegateTo ? delegate === delegateTo && delegatedAmount > 0n : null,
    };

    this.#audit.log('getExternalTokenPosition', 'external', {
      owner: ownerAddress.slice(0, 8) + '...',
      mint: tokenMint.slice(0, 8) + '...',
      delegateTo: delegateTo ? delegateTo.slice(0, 8) + '...' : null,
    }, JSON.stringify({
      rawBalance: result.rawBalance,
      delegatedAmount: result.delegatedAmount,
      delegationSatisfied: result.delegationSatisfied,
    }), performance.now() - t0);
    return result;
  }

  // ═══════════════════════════════════════
  // T1B.1 — Send Tokens
  // ═══════════════════════════════════════

  /**
   * Send native SOL.
   *
   * SECURITY:
   * - Amount validated: > 0, <= MAX_SOL_TRANSFER, valid BigInt
   * - Recipient validated as base58 Solana address
   * - WDK handles signing internally
   * - Fee capped by transferMaxFee in WDK config
   *
   * @param {string} agentId
   * @param {string} to recipient base58 address
   * @param {string|bigint} lamports amount in lamports
   * @returns {Promise<{txHash: string, fee: string}>}
   */
  async sendSol(agentId, to, lamports) {
    validate.agentId(agentId);
    validate.solanaAddress(to);
    const amount = validate.amount(lamports, MAX_SOL_TRANSFER);
    this.#checkRate(agentId);
    const agent = this.#requireAgent(agentId);

    // AUDIT: Prevent sending to self (common mistake, wastes fees)
    if (to === agent.address) {
      throw new Error('SELF_TRANSFER: Cannot send tokens to own address');
    }

    const t0 = performance.now();

    const result = await agent.account.sendTransaction({
      to,
      value: amount,
    });

    const out = {
      txHash: result.hash,
      fee: String(result.fee ?? '0'),
    };

    this.#audit.log('sendSol', agentId, {
      to: to.slice(0, 8) + '...',
      lamports: String(amount),
    }, out.txHash, performance.now() - t0);

    return out;
  }

  /**
   * Send SPL tokens.
   *
   * SECURITY:
   * - Amount validated: > 0, <= MAX_SPL_TRANSFER
   * - Both recipient and mint validated as base58
   * - Uses WDK SPL transfer (not raw instruction building)
   *
   * @param {string} agentId
   * @param {string} to recipient
   * @param {string|bigint} amount in token smallest units
   * @param {string} tokenMint SPL token mint address
   * @returns {Promise<{txHash: string, fee: string}>}
   */
  async sendToken(agentId, to, amount, tokenMint) {
    validate.agentId(agentId);
    validate.solanaAddress(to);
    validate.solanaAddress(tokenMint);
    const validAmount = validate.amount(amount, MAX_SPL_TRANSFER);
    this.#checkRate(agentId);
    const agent = this.#requireAgent(agentId);

    if (to === agent.address) {
      throw new Error('SELF_TRANSFER: Cannot send tokens to own address');
    }

    const t0 = performance.now();

    const result = await agent.account.sendTransaction({
      to,
      value: validAmount,
      tokenMint,
    });

    const out = {
      txHash: result.hash,
      fee: String(result.fee ?? '0'),
    };

    this.#audit.log('sendToken', agentId, {
      to: to.slice(0, 8) + '...',
      amount: String(validAmount),
      mint: tokenMint.slice(0, 8) + '...',
    }, out.txHash, performance.now() - t0);

    return out;
  }

  /**
   * Estimate transaction fee before sending.
   * @param {string} agentId
   * @param {string} to
   * @param {string|bigint} lamports
   * @returns {Promise<{feeLamports: string, feeSol: string}>}
   */
  async estimateFee(agentId, to, lamports) {
    validate.agentId(agentId);
    validate.solanaAddress(to);
    const amount = validate.amount(lamports, MAX_SOL_TRANSFER);
    const agent = this.#requireAgent(agentId);

    const quote = await agent.account.quoteSendTransaction({ to, value: amount });

    return {
      feeLamports: String(quote.fee),
      feeSol: (Number(quote.fee) / 1e9).toFixed(9),
    };
  }

  // ═══════════════════════════════════════
  // Lookups
  // ═══════════════════════════════════════

  /** Get wallet address for an agent. Never returns seeds or keys. */
  getAddress(agentId) {
    validate.agentId(agentId);
    return this.#requireAgent(agentId).address;
  }

  /** List all agent wallets (addresses only). */
  listWallets() {
    return Array.from(this.#agents.entries()).map(([agentId, a]) => ({
      agentId,
      address: a.address,
      chain: a.chain,
      createdAt: a.createdAt,
    }));
  }

  /** Reverse lookup for a managed wallet by public address. */
  getAgentIdByAddress(address) {
    validate.solanaAddress(address);
    for (const [agentId, record] of this.#agents.entries()) {
      if (record.address === address) return agentId;
    }
    return null;
  }

  /** Check if an agent wallet exists. */
  hasWallet(agentId) {
    return this.#agents.has(agentId);
  }

  /** Get audit log entries. */
  getAuditLog(count = 50) {
    return this.#audit.getRecent(count);
  }

  /** Get the underlying WDK account (for advanced ops like approve). */
  getAccount(agentId) {
    validate.agentId(agentId);
    return this.#requireAgent(agentId).account;
  }

  /** Expose the configured RPC URL for read/write helpers built on top of WDK. */
  getRpcUrl() {
    return this.#config.rpcUrl;
  }

  async restorePersistedWallets() {
    let raw;
    try {
      raw = await readFile(this.#walletStorePath, 'utf8');
    } catch {
      return [];
    }

    const parsed = JSON.parse(raw);
    const wallets = Array.isArray(parsed?.wallets) ? parsed.wallets : [];
    const restored = [];

    for (const entry of wallets) {
      if (!entry?.agentId) continue;
      if (this.#agents.has(entry.agentId)) continue;

      validate.agentId(entry.agentId);
      const seed = this.#restoreSeed(entry);
      const record = await this.#instantiateWalletRecord(entry.agentId, seed, entry.createdAt || Date.now());
      this.#agents.set(entry.agentId, record);
      this.#seeds.set(entry.agentId, seed);
      restored.push({ agentId: entry.agentId, address: record.address });
    }

    return restored;
  }

  // ═══════════════════════════════════════
  // Private
  // ═══════════════════════════════════════

  #requireAgent(agentId) {
    const agent = this.#agents.get(agentId);
    if (!agent) throw new Error(`AGENT_NOT_FOUND: "${agentId}" — create wallet first`);
    return agent;
  }

  async #rpc(method, params) {
    const response = await fetch(this.#config.rpcUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: `${method}-${Date.now()}`,
        method,
        params,
      }),
    });

    if (!response.ok) {
      throw new Error(`RPC_HTTP_ERROR: ${response.status}`);
    }

    const payload = await response.json();
    if (payload.error) {
      throw new Error(`RPC_ERROR: ${payload.error.message || method}`);
    }

    return payload.result;
  }

  async #instantiateWalletRecord(agentId, seed, createdAt = Date.now()) {
    const wdk = new WDK(seed).registerWallet('solana', WalletManagerSolana, {
      rpcUrl:         this.#config.rpcUrl,
      wsUrl:          this.#config.wsUrl,
      transferMaxFee: this.#config.transferMaxFee,
    });

    const account = await wdk.getAccount('solana', 0);
    const address = await account.getAddress();
    validate.solanaAddress(address);

    return Object.freeze({
      wdk,
      account,
      address,
      chain: 'solana',
      createdAt,
    });
  }

  async #persistWallets() {
    await mkdir(this.#config.stateDir, { recursive: true });
    const wallets = Array.from(this.#seeds.entries()).map(([agentId, seed]) => {
      const encrypted = this.#encryptSeed(seed);
      return {
        agentId,
        seedCiphertext: encrypted.ciphertext,
        seedIv: encrypted.iv,
        seedTag: encrypted.tag,
        createdAt: this.#agents.get(agentId)?.createdAt || Date.now(),
      };
    });
    await writeFile(this.#walletStorePath, JSON.stringify({ wallets }, null, 2), 'utf8');
  }

  #getWalletStateKey() {
    const secret = this.#config.walletStateEncryptionKey;
    if (!secret) {
      throw new Error('WALLET_STATE_ENCRYPTION_KEY_REQUIRED: configure WALLET_STATE_ENCRYPTION_KEY before persisting agent wallets');
    }
    return createHash('sha256').update(secret).digest();
  }

  #encryptSeed(seed) {
    const iv = randomBytes(12);
    const key = this.#getWalletStateKey();
    const cipher = createCipheriv('aes-256-gcm', key, iv);
    const ciphertext = Buffer.concat([cipher.update(seed, 'utf8'), cipher.final()]);
    const tag = cipher.getAuthTag();
    return {
      ciphertext: ciphertext.toString('base64'),
      iv: iv.toString('base64'),
      tag: tag.toString('base64'),
    };
  }

  #decryptSeed(ciphertext, iv, tag) {
    const key = this.#getWalletStateKey();
    const decipher = createDecipheriv(
      'aes-256-gcm',
      key,
      Buffer.from(iv, 'base64'),
    );
    decipher.setAuthTag(Buffer.from(tag, 'base64'));
    const plaintext = Buffer.concat([
      decipher.update(Buffer.from(ciphertext, 'base64')),
      decipher.final(),
    ]);
    return plaintext.toString('utf8');
  }

  #restoreSeed(entry) {
    if (entry.seedCiphertext && entry.seedIv && entry.seedTag) {
      return this.#decryptSeed(entry.seedCiphertext, entry.seedIv, entry.seedTag);
    }
    if (entry.seed) {
      return entry.seed;
    }
    throw new Error(`WALLET_STATE_CORRUPT: missing encrypted seed material for agent "${entry.agentId}"`);
  }

  /** AUDIT[S8]: Sliding window rate limiter per agent. */
  #checkRate(agentId) {
    const now = Date.now();
    const hourAgo = now - 3_600_000;
    let bucket = this.#rateBuckets.get(agentId);
    if (!bucket) {
      bucket = [];
      this.#rateBuckets.set(agentId, bucket);
    }
    // Evict old entries
    while (bucket.length > 0 && bucket[0] < hourAgo) bucket.shift();
    if (bucket.length >= this.#config.rateLimitPerHour) {
      throw new Error(`RATE_LIMIT: Agent "${agentId}" exceeded ${this.#config.rateLimitPerHour} ops/hour`);
    }
    bucket.push(now);
  }
}

export default WalletService;
